---
# tasks file for downloader

- name: Download Remote Urls
  become: true
  become_user: "{{ download_save_user }}"
  ansible.builtin.get_url:
    url: "{{ downloader_item.url }}"
    dest: "{{ download_save_location }}/{{ downloader_item.name }}"
    owner: "{{ download_save_user }}"
    timeout: "{{ download_timeout }}"
    mode: 0644
  loop: "{{ download_remote_urls }}"
  loop_control:
    loop_var: downloader_item
  tags:
    - downloader
