---
- name: Install ClamWatch Service Plist
  become: true
  ansible.builtin.template:
    src: services/clamwatch/net.clamav.clamwatch.plist.j2
    dest: /Library/LaunchDaemons/net.clamav.clamwatch.plist
    mode: "0644"
    owner: root
    group: wheel
  notify:
    - Restart Clamwatch

- name: Install ClamWatch Script
  become: true
  ansible.builtin.template:
    src: services/clamwatch/clamwatch.sh.j2
    dest: "{{ brew_prefix }}/bin/clamwatch"
    mode: "0755"
    owner: root
    group: wheel
  notify:
    - Restart Clamwatch
