---
- name: Add Colima Launch Script
  become: true
  ansible.builtin.template:
    src: "service/colima-start-fg.sh.j2"
    dest: "/usr/local/bin/colima-start-fg.sh"
    mode: "0755"
    owner: "{{ colima_service_user }}"
    group: "staff"
  notify:
    - "Restart Colima Service"

- name: Add LaunchAgents Folder
  become: true
  ansible.builtin.file:
    dest: "/Users/{{ colima_service_user }}/Library/LaunchAgents"
    mode: "0700"
    owner: "{{ colima_service_user }}"
    group: "staff"
    state: "directory"
  notify:
    - "Restart Colima Service"

- name: Add Colima Launch Agent Plist
  become: true
  ansible.builtin.template:
    src: "service/com.github.abiosoft.colima.plist.j2"
    dest: "/Users/{{ colima_service_user }}/Library/LaunchAgents/com.github.abiosoft.colima.plist"
    mode: "0640"
    owner: "{{ colima_service_user }}"
    group: "staff"
  notify:
    - "Restart Colima Service"
