---
- name: Check Colima Stderr Log File exists
  become: true
  ansible.builtin.stat:
    path: "{{ colima_service_stderr_log_file }}"
  register: colima_service_stderr_log_file_stat

- name: Check Colima Stdout Log File Exists
  become: true
  ansible.builtin.stat:
    path: "{{ colima_service_stdout_log_file }}"
  register: colima_service_stdout_log_file_stat

- name: Create Colima Stderr Log File
  become: true
  ansible.builtin.file:
    path: "{{ colima_service_stderr_log_file }}"
    state: touch
    mode: "0640"
    owner: "{{ colima_service_user }}"
    group: admin
  when: not colima_service_stderr_log_file_stat.stat.exists

- name: Create Colima Stdout Log File
  become: true
  ansible.builtin.file:
    path: "{{ colima_service_stdout_log_file }}"
    state: touch
    mode: "0640"
    owner: "{{ colima_service_user }}"
    group: admin
  when: not colima_service_stdout_log_file_stat.stat.exists
