---
galaxy_info:
  role_name: homebrew_retry
  namespace: osx_provisioner
  author: Niall Byrne
  description: Ansible role that installs homebrew apps, casks and taps in a retry loop to deal with connectivity issues.
  company: Shared Vision Solutions
  license: MIT
  platforms:
    - name: macOS
      versions:
        - Monterey
        - Big-Sur
    - name: MacOSX
      versions:
        - "10.15"
        - "10.14"
  min_ansible_version: 2.11.0
  galaxy_tags:
    - homebrew
    - mac
    - osx

dependencies: []
