---
# tasks file for clamav

- name: Install ClamAV From HomeBrew
  become: true
  become_user: "{{ brew_user }}"
  community.general.homebrew:
    name:
      - clamav
      - fswatch
    state: upgraded
  retries: "{{ clamav_homebrew_retries }}"
  delay: 3
  register: clamav_install
  until: clamav_install is not failed
  tags:
    - clamav

- name: Remove Legacy Services
  ansible.builtin.include_tasks:
    file: "legacy_services/remove.yml"
  with_items:
    - "clamav.freshclam"
    - "clamav.clamd"
    - "clamav.clamwatch"
  loop_control:
    loop_var: "clamav_legacy_service"
  tags:
    - clamav

- name: Install Clamd Service
  ansible.builtin.include_tasks:
    file: "services/clamd.yml"
  tags:
    - clamav

- name: Install Clamwatch Service
  ansible.builtin.include_tasks:
    file: "services/clamwatch.yml"
  when: clamav_clamwatch
  tags:
    - clamav

- name: Install Freshclam Service
  ansible.builtin.include_tasks:
    file: "services/freshclam.yml"
  tags:
    - clamav
