---
namespace: osx_provisioner
name: collection
version: "2.2.0"
readme: README.md

authors:
  - Niall Byrne <niall@niallbyrne.ca>

description: A collection of OSX automation tools for Ansible.

# Either a single license or a list of licenses for content inside of a collection. Ansible Galaxy currently only
# accepts L(SPDX,https://spdx.org/licenses/) licenses. This key is mutually exclusive with 'license_file'
license:
  - MIT

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags:
  - apple
  - brew
  - homebrew
  - imac
  - ios
  - mac
  - macbook
  - macmini
  - macos
  - osx
  - server
  - tools

dependencies:
  community.general: ">=6.3.0"
  geerlingguy.mac: ">=2.1.1,<3.0.0"

repository: https://github.com/osx-provisioner/collection
documentation: https://github.com/osx-provisioner/collection
homepage: https://www.niallbyrne.ca
issues: https://github.com/osx-provisioner/collection/issues

build_ignore: []
