---
- name: Install FreshClam Service Configuration
  become: true
  ansible.builtin.template:
    src: net.clamav.freshclam.plist.j2
    dest: /Library/LaunchDaemons/net.clamav.freshclam.plist
    mode: "0644"
    owner: root
    group: wheel
  notify:
    - Update Virus Definitions
    - Restart Freshclam

- name: Install FreshClam Daemon Configuration
  become: true
  ansible.builtin.template:
    src: freshclam.conf.j2
    dest:  "{{ clamav_freshclam_config_file }}"
    mode: "0644"
    owner: _clamav
    group: _clamav
  notify:
    - Update Virus Definitions
    - Restart Freshclam

- name: Install Clamd Service Configuration
  become: true
  ansible.builtin.template:
    src: net.clamav.clamd.plist.j2
    dest: /Library/LaunchDaemons/net.clamav.clamd.plist
    mode: "0644"
    owner: root
    group: wheel
  notify:
    - Update Virus Definitions
    - Restart Clamd

- name: Install Clamd Daemon Configuration
  become: true
  ansible.builtin.template:
    src: clamd.conf.j2
    dest: "{{ clamav_clamd_config_file }}"
    mode: "0644"
    owner: root
    group: wheel
  notify:
    - Update Virus Definitions
    - Restart Clamd
