---
- name: Set CI Machine Type
  ansible.builtin.set_fact:
    ansible_machine: "{{ lookup('env', 'PLATFORM') }}"

- name: Load Default Var Content
  ansible.builtin.include_vars: "../../../defaults/main.yml"

- name: Check clamd is installed
  ansible.builtin.stat:
    path: "{{ brew_prefix }}/sbin/clamd"
  register: clamav_molecule_clamd_file

- name: Check freshclam is installed
  ansible.builtin.stat:
    path: "{{ brew_prefix }}/bin/freshclam"
  register: clamav_molecule_freshclam_file

- name: Check clamwatch is installed
  ansible.builtin.stat:
    path: "{{ brew_prefix }}/bin/clamwatch"
  register: clamav_molecule_clamwatch_file
