---
- name: Include elliotweiser.osx-command-line-tools
  ansible.builtin.include_role:
    name: "elliotweiser.osx-command-line-tools"

- name: Include geerlingguy.mac.homebrew
  ansible.builtin.include_role:
    name: "geerlingguy.mac.homebrew"
