---
- name: Set CI Machine Type
  ansible.builtin.set_fact:
    ansible_machine: "{{ lookup('env', 'PLATFORM') }}"

- name: Load Default Var Content
  ansible.builtin.include_vars: "../../../defaults/main.yml"

- name: Create Process Match Strings
  ansible.builtin.set_fact:
    clamav_molecule_process_matchers:
      clamd: '{{ brew_prefix }}/sbin/clamd --foreground -c {{ clamav_clamd_config_file }}'
      clamwatch: '/bin/bash {{ brew_prefix }}/bin/clamwatch {{ clamav_clamwatch_target_folder }} {{ clamav_clamwatch_quarantine_folder }} {{ clamav_clamwatch_log_file }}'
      freshclam: '{{ brew_prefix }}/bin/freshclam --daemon --foreground --config-file {{ clamav_freshclam_config_file }}'

- name: Wait For Process to Start
  ansible.builtin.command: "ps -u {{ clamav_expected_process.user }}"
  changed_when: false
  retries: 10
  delay: 3
  register: clamav_molecule_root_processes
  until: "clamav_molecule_process_matchers[clamav_expected_process.name] in clamav_molecule_root_processes.stdout"
  with_items: "{{ clamav_molecule_installed_binaries }}"
  loop_control:
    loop_var: clamav_expected_process
