---
- name: Converge
  hosts: all
  connection: local
  tasks:

    - name: Expect Failure
      block:

        - name: Setup Scenario
          ansible.builtin.include_tasks: "../common/tasks/setup.yml"

        - name: Include osx_provisioner.collection.colima
          ansible.builtin.include_role:
            name: "osx_provisioner.collection.colima"

        - name: Check execution halted
          ansible.builtin.fail:
            msg: "The playbook should stop execution before this step."
          register: playbook_exception

      rescue:

        - name: Disable Colima Handler
          ansible.builtin.set_fact:
            colima_handler_disable: true

        - name: Ensure the role failed
          ansible.builtin.assert:
            that:
              - playbook_exception is not defined
