---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Check File System Content
      ansible.builtin.include_tasks: "../common/tasks/files.yml"

    - name: Check Processes
      ansible.builtin.include_tasks: "../common/tasks/processes.yml"

    - name: Assert the binaries are symlinked correctly
      ansible.builtin.assert:
        that:
          - clamav_molecule_clamd_file.stat.executable
          - clamav_molecule_freshclam_file.stat.executable
          - clamav_molecule_clamwatch_file.stat.executable
        msg: "The binaries were not symlinked.  Check the homebrew install."

    - name: Assert the processes as running
      ansible.builtin.assert:
        that:
          - clamav_molecule_root_process_match_clamd in clamav_molecule_root_processes.stdout
          - clamav_molecule_root_process_match_clamwatch in clamav_molecule_root_processes.stdout
          - clamav_molecule_user_processes_match_freshclam in clamav_molecule_user_processes.stdout
        msg: "The services did not start correctly."
