---
- name: Converge
  hosts: all
  connection: local
  tasks:

    - name: Setup Scenario
      ansible.builtin.include_tasks: "../common/tasks/setup.yml"
      tags:
        - molecule-idempotence-notest

    - name: Mock Previous Install Data
      become: true
      ansible.builtin.copy:
        dest: "{{ jumpcloud_agent_location }}"
        content: "Mock Previous Install\n"
        mode: 0644
      tags:
        - molecule-idempotence-notest

    - name: Include osx_provisioner.collection.jumpcloud
      ansible.builtin.include_role:
        name: "osx_provisioner.collection.jumpcloud"
      tags:
        - molecule-idempotence-notest
