---
dependency:
  name: galaxy
  options:
    role-file: ../../requirements.yml
    requirements-file: ../../requirements.yml
    timeout: "120"
    force: false
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
      ansible_sudo_pass: "${ANSIBLE_SUDO_PASSWORD}"
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    privilege_escalation:
      become_method: sudo
scenario:
  create_sequence:
    - dependency
    - create
    - prepare
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence, disabled for update as installer will always run
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
