---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      ansible.builtin.include_vars: "vars/main.yml"

    - name: Verify the Homeshick Install
      ansible.builtin.include_tasks: "../common/tasks/verify_homeshick.yml"
