---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Display Logs For Troubleshooting Failures
      block:

        - name: Verify Binaries
          ansible.builtin.include_tasks: "../common/tasks/verify_binaries.yml"

        - name: Verify Docker
          ansible.builtin.include_tasks: "../common/tasks/verify_docker.yml"

      always:

        - name: Display Logs
          ansible.builtin.include_tasks: "../common/tasks/display_logs.yml"
