---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      ansible.builtin.include_vars: "vars/main.yml"

    - name: Verify the Homeshick Install
      ansible.builtin.include_tasks: "../common/tasks/verify_homeshick.yml"

    - name: Verify the Dotfiles Install
      ansible.builtin.include_tasks: "../common/tasks/verify_dotfiles.yml"

    - name: Check the user .bashrc file
      ansible.builtin.stat:
        path: "{{ homeshick_user_home }}/.bashrc"
      register: homeshick_molecule_bashrc_symlink

    - name: Assert the user .bashrc is symlinked and is readable
      ansible.builtin.assert:
        that:
          - homeshick_molecule_bashrc_symlink.stat.islnk
          - homeshick_molecule_bashrc_symlink.stat.readable
        msg: "The user .bashrc file should be symlinked and readable."
