---
- name: Install asdf Global Homebrew Packages
  become: True
  become_user: "{{ asdf_user }}"
  community.general.homebrew:
    name: "{{ asdf_darwin_global_dependencies }}"
    state: upgraded
  retries: "{{ asdf_homebrew_retries }}"
  delay: 3
  register: asdf_install_darwin_global_dependencies
  until: asdf_install_darwin_global_dependencies is not failed
  when: ansible_os_family == "Darwin"

- name: Check for existing asdf install
  become: True
  become_user: "{{ asdf_user }}"
  ansible.builtin.git:
    repo: "{{ asdf_git_repository_url }}"
    dest: "{{ asdf_user_home }}/.asdf"
    version: "{{ asdf_version }}"
    clone: no
  register: asdf_git_results

- name: Install asdf
  become: True
  become_user: "{{ asdf_user }}"
  ansible.builtin.git:
    repo: "{{ asdf_git_repository_url }}"
    dest: "{{ asdf_user_home }}/.asdf"
    version: "{{ asdf_version }}"
  when: not asdf_git_results.before
