---
- name: Add Docker CLI Plugin Folder
  become: true
  ansible.builtin.file:
    dest: "/Users/{{ colima_service_user }}/.docker/cli-plugins"
    mode: "0751"
    owner: "{{ colima_service_user }}"
    group: "staff"
    state: "directory"

- name: Enable Docker-Compose Support
  become: true
  become_user: "{{ colima_service_user }}"
  ansible.builtin.file:
    src: "{{ brew_prefix }}/bin/docker-compose"
    dest: "/Users/{{ colima_service_user }}/.docker/cli-plugins/docker-compose"
    force: true
    follow: false
    state: "link"

- name: Add Colima Docker Symlink
  become: true
  ansible.builtin.file:
    src: "/Users/{{ colima_service_user }}/.colima/{{ colima_service_default_profile }}/docker.sock"
    dest: "/var/run/docker.sock"
    mode: "0751"
    owner: "root"
    group: "daemon"
    state: link
    follow: false
    force: true
