---

- name: Test With Fail Fast on Packages Enabled
  block:

    - name: Include osx_provisioner.collection.homebrew_retry
      ansible.builtin.include_role:
        name: "osx_provisioner.collection.homebrew_retry"
      vars:
        brew_packages:
          - non_existent_non_existent_non_existent

  rescue:

    - name: Assert Retry Did Not Fire (Test With Fail Fast on Packages Enabled)
      ansible.builtin.assert:
        that:
          - homebrew_retry_install_packages.attempts == 1
        msg: "This task should NOT have been retried."


- name: Test With Fail Fast on Packages Disabled
  block:

    - name: Include osx_provisioner.collection.homebrew_retry
      ansible.builtin.include_role:
        name: "osx_provisioner.collection.homebrew_retry"
      vars:
        brew_fail_matchers:
          packages: "DISABLED"
        brew_packages:
          - non_existent_non_existent_non_existent
        brew_retries: 2

  rescue:

    - name: Assert Retry Fired (Test With Fail Fast on Packages Disabled)
      ansible.builtin.assert:
        that:
          - homebrew_retry_install_packages.attempts == 2
        msg: "This task should have been retried."
