---
# handlers file for clamav

- name: Stop Freshclam Service
  become: true
  community.general.launchd:
    name: "net.clamav.freshclam"
    state: stopped
  listen:
    - "Update Virus Definitions"

- name: Update Virus Definitions
  become: true
  ansible.builtin.command: "{{ brew_prefix }}/bin/freshclam --config-file '{{ clamav_freshclam_config_file }}'"
  changed_when: true
  listen: "Update Virus Definitions"

- name: Restart Clamd Service
  become: true
  community.general.launchd:
    name: "net.clamav.clamd"
    enabled: true
    state: restarted
  listen: "Restart Clamd"

- name: Restart Freshclam Service
  become: true
  community.general.launchd:
    name: "net.clamav.freshclam"
    enabled: true
    state: restarted
  listen: "Restart Freshclam"

- name: Restart Clamwatch Service
  become: true
  community.general.launchd:
    name: "net.clamav.clamwatch"
    enabled: true
    state: restarted
  listen: "Restart Clamwatch"
