---
- name: Clean Up
  hosts: all
  gather_facts: false
  tasks:

    - name: Setup Scenario
      ansible.builtin.include_tasks: "../common/tasks/setup.yml"

    - name: Clean Up
      ansible.builtin.file:
        path: "{{ download_save_location }}/{{ downloader_item.name }}"
        state: absent
      loop: "{{ download_remote_urls }}"
      loop_control:
        loop_var: downloader_item
