---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Load Default Variables
      ansible.builtin.include_vars: ../../defaults/main.yml
    - name: Load Scenario Variables
      ansible.builtin.include_vars: vars/main.yml
    - name: Read Variables from Test Run
      become: true
      ansible.builtin.slurp:
        src: /tmp/mock_installer_arguments
      register: jump_cloud_molecule_results
    - name: Check Mock Install Arguments
      ansible.builtin.assert:
        that:
          - jump_cloud_molecule_results.content | b64decode == "-f -s -k secret_jumpcloud_key\n"
