---
- name: Converge
  hosts: all
  connection: local
  vars:
    clamav_clamwatch: false
  tasks:

    - name: Setup Scenario
      ansible.builtin.include_tasks: "../common/tasks/setup.yml"

    - name: Include osx_provisioner.collection.clamav
      ansible.builtin.include_role:
        name: "osx_provisioner.collection.clamav"
