---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Display Logs For Troubleshooting Failures
      block:

        - name: Define Expected Binaries
          ansible.builtin.set_fact:
            clamav_molecule_installed_binaries:
              - name: clamd
                path: sbin
                user: root
              - name: freshclam
                path: bin
                user: _clamav

        - name: Verify Binaries
          ansible.builtin.include_tasks: "../common/tasks/verify_binaries.yml"

        - name: Verify Processes
          ansible.builtin.include_tasks: "../common/tasks/verify_processes.yml"

        - name: Assert clamwatch Process Not Running
          ansible.builtin.assert:
            that:
              - clamav_molecule_process_matchers.clamwatch not in clamav_molecule_root_processes.results[0].stdout
            msg: "The clamwatch process should NOT be running!"

      always:

        - name: Display Logs
          ansible.builtin.include_tasks: "../common/tasks/display_logs.yml"
