---
# tasks file for homeshick

- name: Check for Homeshick Install
  ansible.builtin.stat:
    path: "{{ homeshick_user_home }}/.homesick/repos/homeshick"
  register: homeshick_stat_result
  tags:
    - homeshick

- name: Clone Homeshick
  become: true
  become_user: "{{ homeshick_user }}"
  ansible.builtin.git:
    repo: https://github.com/andsens/homeshick.git
    dest: "{{ homeshick_user_home }}/.homesick/repos/homeshick"
    version: "{{ homeshick_version }}"
  when: not homeshick_stat_result.stat.exists
  tags:
    - homeshick

- name: Check if the user dotfiles were already installed
  ansible.builtin.stat:
    path: "{{ homeshick_user_home }}/.homesick/repos/{{ homeshick_dotfiles_repo | lower | basename | replace('.git', '') }}"
  register: homeshick_user_dot_files

- name: Install User Dotfiles
  become: true
  become_user: "{{ homeshick_user }}"
  ansible.builtin.command: "{{ homeshick_user_home }}/.homesick/repos/homeshick/bin/homeshick clone {{ homeshick_dotfiles_repo }}"
  changed_when: not homeshick_user_dot_files.stat.exists and homeshick_dotfiles_repo
  when: not homeshick_user_dot_files.stat.exists and homeshick_dotfiles_repo
  tags:
    - homeshick

- name: Link Install Dotfiles (Force)
  become: true
  become_user: "{{ homeshick_user }}"
  ansible.builtin.command: "{{ homeshick_user_home }}/.homesick/repos/homeshick/bin/homeshick link -vf {{ homeshick_dotfiles_repo | lower | basename | replace('.git', '') }}"
  register: homeshick_install_command
  changed_when: "'symlink' in homeshick_install_command.stdout"
  when: homeshick_dotfiles_repo and homeshick_force
  tags:
    - homeshick

- name: Link Install Dotfiles (Without Force)
  become: true
  become_user: "{{ homeshick_user }}"
  ansible.builtin.command: "{{ homeshick_user_home }}/.homesick/repos/homeshick/bin/homeshick link -v {{ homeshick_dotfiles_repo | lower | basename | replace('.git', '') }}"
  register: homeshick_install_command
  changed_when: "'symlink' in homeshick_install_command.stdout"
  when: homeshick_dotfiles_repo and not homeshick_force
  tags:
    - homeshick
