---
# tasks file for homeshick

- name: Create Homeshick CLI Command
  ansible.builtin.set_fact:
    homeshick_cli_command: "{{ homeshick_user_home }}/.homesick/repos/homeshick/bin/homeshick"
  tags:
    - homeshick

- name: Create Homeshick User Repo Name
  ansible.builtin.set_fact:
    homeshick_user_castle_name: "{{ homeshick_dotfiles_repo | lower | basename | replace('.git', '') }}"
  tags:
    - homeshick

- name: Create Homeshick CLI Task Helpers
  ansible.builtin.set_fact:
    homeshick_cli_clone_command: "{{ homeshick_cli_command }} clone {{ homeshick_dotfiles_repo }}"
    homeshick_cli_link_command: "{{ homeshick_cli_command }} link {{ homeshick_force | ternary('-vf', '-v') }} {{ homeshick_user_castle_name }}"
  tags:
    - homeshick

- name: Check for Existing Homeshick Install
  become: true
  become_user: "{{ homeshick_user }}"
  ansible.builtin.git:
    repo: "{{ homeshick_git_repository_url }}"
    dest: "{{ homeshick_user_home }}/.homesick/repos/homeshick"
    version: "{{ homeshick_version }}"
    clone: no
  register: homeshick_git_results
  tags:
    - homeshick

- name: Clone Homeshick
  become: true
  become_user: "{{ homeshick_user }}"
  ansible.builtin.git:
    repo: "{{ homeshick_git_repository_url }}"
    dest: "{{ homeshick_user_home }}/.homesick/repos/homeshick"
    version: "{{ homeshick_version }}"
  when: not homeshick_git_results.before
  tags:
    - homeshick

- name: Check if User Dotfiles Castle Already Installed
  ansible.builtin.stat:
    path: "{{ homeshick_user_home }}/.homesick/repos/{{ homeshick_user_castle_name }}"
  register: homeshick_user_castle_stat_results
  tags:
    - homeshick

- name: Debug Homeshick Clone Command
  ansible.builtin.debug:
    msg: "Executing: {{ homeshick_cli_clone_command }}"
  when: not homeshick_user_castle_stat_results.stat.exists and homeshick_dotfiles_repo
  tags:
    - homeshick

- name: Install User Dotfile Castle
  become: true
  become_user: "{{ homeshick_user }}"
  ansible.builtin.command: "{{ homeshick_cli_clone_command }}"
  changed_when: true
  when: not homeshick_user_castle_stat_results.stat.exists and homeshick_dotfiles_repo
  tags:
    - homeshick

- name: Debug Homeshick Link Command
  ansible.builtin.debug:
    msg: "Executing: {{ homeshick_cli_link_command }}"
  when: homeshick_dotfiles_repo
  tags:
    - homeshick

- name: Link User Dotfile Castle
  become: true
  become_user: "{{ homeshick_user }}"
  ansible.builtin.command: "{{ homeshick_cli_link_command }}"
  register: homeshick_install_command
  changed_when: "'symlink' in homeshick_install_command.stdout"
  when: homeshick_dotfiles_repo
  tags:
    - homeshick
