---
- name: Add Colima Configuration Folder
  become: true
  ansible.builtin.file:
    path: "/Users/{{ colima_user }}/.colima/{{ colima_profile }}"
    mode: "0755"
    owner: "{{ colima_user }}"
    group: "staff"
    state: "directory"
  with_items: "{{ colima_profiles }}"
  loop_control:
    loop_var: "colima_profile"
  notify:
    - "Enable Colima Service"

- name: Hash Previous Colima Configuration
  ansible.builtin.stat:
    path: "/Users/{{ colima_user }}/.colima/{{ colima_default_profile }}/colima.yaml"
  register: colima_previous_configuration

- name: Add Colima Configuration
  become: true
  ansible.builtin.template:
    src: "./templates/colima.yaml.j2"
    dest: "/Users/{{ colima_user }}/.colima/{{ colima_profile }}/colima.yaml"
    mode: "0644"
    owner: "{{ colima_user }}"
    group: "staff"
  with_items: "{{ colima_profiles }}"
  loop_control:
    loop_var: "colima_profile"
  changed_when: false

- name: Add Colima Docker Symlink
  become: true
  ansible.builtin.file:
    src: "/Users/{{ colima_user }}/.colima/{{ colima_default_profile }}/docker.sock"
    dest: "/var/run/docker.sock"
    mode: "0751"
    owner: "root"
    group: "daemon"
    state: link
    follow: false
    force: true
  notify:
    - "Enable Colima Service"

- name: Bootstrap Colima
  become: true
  become_user: "{{ colima_user }}"
  register: colima_bootstrap_service
  ansible.builtin.command: colima start
  changed_when: "'already running' not in colima_bootstrap_service.stderr"
  failed_when: "'config load failed' in colima_bootstrap_service.stderr or colima_bootstrap_service.rc != 0"
  notify:
    - "Stop Bootstrap Process"

- name: Hash New Colima Configuration
  ansible.builtin.stat:
    path: "/Users/{{ colima_user }}/.colima/{{ colima_default_profile }}/colima.yaml"
  register: colima_new_configuration

- name: Detect Configuration Change
  ansible.builtin.command: "/bin/echo"
  changed_when: true
  notify:
    - "Enable Colima Service"
  when: not colima_previous_configuration.stat.exists or colima_new_configuration.stat.checksum != colima_previous_configuration.stat.checksum
