---
# tasks file for role-colima
- name: Create Colima Profiles List
  ansible.builtin.set_fact:
    colima_service_profiles:
      - "{{ colima_service_default_profile }}"
  tags:
    - colima

- name: Create Colima Profiles List
  ansible.builtin.set_fact:
    colima_service_profiles: "{{ colima_service_profiles + colima_service_additional_profiles }}"
  tags:
    - colima

- name: Install Colima From HomeBrew
  become: true
  become_user: "{{ colima_service_user }}"
  community.general.homebrew:
    name:
      - colima
      - docker
      - docker-compose
    state: upgraded
  retries: "{{ colima_homebrew_retries }}"
  delay: 3
  register: colima_install_colima
  until: colima_install_colima is not failed
  notify:
    - "Restart Colima Service"
  tags:
    - colima

- name: Configure Colima Service
  ansible.builtin.import_tasks: "configuration/service.yml"
  tags:
    - colima

- name: Configure Docker Compose Support
  ansible.builtin.import_tasks: "configuration/compose.yml"
  tags:
    - colima

- name: Setup Service Logging
  ansible.builtin.import_tasks: "service/logging.yml"
  tags:
    - colima

- name: Install Service
  ansible.builtin.import_tasks: "service/plist.yml"
  tags:
    - colima
