---
# tasks file for role-colima
- name: Create Colima Profiles List
  ansible.builtin.set_fact:
    colima_profiles:
      - "{{ colima_default_profile }}"
  tags:
    - colima

- name: Create Colima Profiles List
  ansible.builtin.set_fact:
    colima_profiles: "{{ colima_profiles + colima_additional_profiles }}"
  tags:
    - colima

- name: Install Colima From HomeBrew
  become: true
  become_user: "{{ colima_user }}"
  community.general.homebrew:
    name:
      - colima
      - docker
    state: upgraded
  retries: "{{ colima_homebrew_retries }}"
  delay: 3
  register: colima_install_colima
  until: colima_install_colima is not failed
  notify:
    - "Enable Colima Service"
  tags:
    - colima

- name: Configure Colima
  ansible.builtin.import_tasks: "configuration.yml"
  tags:
    - colima

- name: Setup Service Logging
  ansible.builtin.import_tasks: "service/logging.yml"
  tags:
    - colima

- name: Install Service
  ansible.builtin.import_tasks: "service/plist.yml"
  tags:
    - colima
