---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      ansible.builtin.include_vars: "vars/main.yml"

    - name: Check Spotify was installed
      ansible.builtin.stat:
        path: "{{ brew_targeted_casks_location }}/Spotify.app/Contents/MacOS/Spotify"
      register: homebrew_retry_molecule_spotify_file

    - name: Check Spotify App Permissions
      ansible.builtin.stat:
        path: "{{ brew_targeted_casks_location }}/Spotify.app"
      register: homebrew_retry_molecule_spotify_app

    - name: Assert Spotify was Installed Correctly
      ansible.builtin.assert:
        that:
          - homebrew_retry_molecule_spotify_file.stat.exists
          - homebrew_retry_molecule_spotify_file.stat.executable
          - homebrew_retry_molecule_spotify_app.stat.mode == "0775"
          - homebrew_retry_molecule_spotify_app.stat.gr_name == brew_targeted_casks_group
          - homebrew_retry_molecule_spotify_app.stat.pw_name == brew_user
        msg: "The Spotify binary must exist and be executable, and have the targeted permissions."
