---
# handlers file for role-colima

- name: Shutdown Bootstrapped Colima
  become: true
  become_user: "{{ colima_service_user }}"
  ansible.builtin.command: colima stop
  changed_when: true
  when: colima_handler_disable is not defined
  listen: "Stop Bootstrap Process"

- name: Restart Colima Service
  become: true
  become_user: "{{ colima_service_user }}"
  community.general.launchd:
    name: "com.github.abiosoft.colima"
    enabled: true
    state: restarted
  when: colima_handler_disable is not defined
  listen: "Restart Colima Service"
