---
- name: Check Packet Filter Stderr Logfile exists
  become: true
  ansible.builtin.stat:
    path: "{{ firewall_service_stderr_log_file }}"
  register: firewall_service_stderr_log_file_stat

- name: Check Packet Filter Stdout Logfile Exists
  become: true
  ansible.builtin.stat:
    path: "{{ firewall_service_stdout_log_file }}"
  register: firewall_service_stdout_log_file_stat

- name: Create Packet Filter Stderr Logfile
  become: true
  ansible.builtin.file:
    path: "{{ firewall_service_stderr_log_file }}"
    state: touch
    mode: "0640"
    owner: "root"
    group: "wheel"
  when: not firewall_service_stderr_log_file_stat.stat.exists

- name: Create Packet Filter Stdout Logfile
  become: true
  ansible.builtin.file:
    path: "{{ firewall_service_stdout_log_file }}"
    state: touch
    mode: "0640"
    owner: "root"
    group: "wheel"
  when: not firewall_service_stdout_log_file_stat.stat.exists
