---
# User Cask Installation

- name: Create User Application Directory
  become: True
  ansible.builtin.file:
    path: '{{ brew_user_casks_location }}'
    owner: "{{ brew_user }}"
    mode: '0700'
    state: directory
  when: brew_user_casks|length > 0
  tags:
    - homebrew_retry
    - homebrew_retry-user-casks

- name: Install Homebrew User Only Casks
  become: True
  become_user: "{{ brew_user }}"
  community.general.homebrew_cask:
    install_options: 'appdir={{ brew_user_casks_location }}'
    name: "{{ brew_user_casks }}"
    # Upgrades Disabled Here Due to: https://github.com/ansible-collections/community.general/issues/1647
    state: present
    accept_external_apps: yes
    sudo_password: "{{ brew_sudo_password }}"
  retries: "{{ brew_retries }}"
  delay: 3
  register: homebrew_retry_install_user_casks
  until: homebrew_retry_install_user_casks is not failed
  when: brew_user_casks|length > 0
  tags:
    - homebrew_retry
    - homebrew_retry-user-casks
