---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      ansible.builtin.include_vars: "vars/main.yml"

    - name: Verify Packages
      ansible.builtin.include_tasks: "../common/tasks/verify_packages.yml"
      with_items:
        - name: telnet
          path: bin
      loop_control:
        loop_var: "homebrew_retry_molecule_verification_package"

    - name: Verify Casks
      ansible.builtin.include_tasks: "../common/tasks/verify_casks.yml"
      with_items:
        - name: "AppCleaner"
          path: "/Applications"
          app_folder_mode: "0755"
        - name: "Transmission"
          path: "{{ brew_user_casks_location }}"
          app_folder_mode: "0755"
        - name: "Spotify"
          path: "{{ brew_targeted_casks_location }}"
          app_folder_mode: "0775"
      loop_control:
        loop_var: "homebrew_retry_molecule_verification_cask"

    - name: Verify Taps
      ansible.builtin.include_tasks: "../common/tasks/verify_taps.yml"
      with_items:
        - name: "gromgit/fuse"
      loop_control:
        loop_var: "homebrew_retry_molecule_verification_tap"
