---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Load Scenario Variables
      ansible.builtin.include_vars: vars/main.yml

    - name: Check telnet was installed
      ansible.builtin.stat:
        path: "/usr/local/bin/telnet"
      register: homebrew_retry_molecule_telnet_file

    - name: Check AppCleaner was installed
      ansible.builtin.stat:
        path: "/Applications/AppCleaner.app/Contents/MacOS/AppCleaner"
      register: homebrew_retry_molecule_cleaner_file

    - name: Check Transmission was installed
      ansible.builtin.stat:
        path: "{{ brew_user_casks_location }}/Transmission.app/Contents/MacOS/Transmission"
      register: homebrew_retry_molecule_transmission

    - name: Check Spotify was installed
      ansible.builtin.stat:
        path: "{{ brew_targeted_casks_location }}/Spotify.app/Contents/MacOS/Spotify"
      register: homebrew_retry_molecule_spotify_file

    - name: Check Spotify App Permissions
      ansible.builtin.stat:
        path: "{{ brew_targeted_casks_location }}/Spotify.app"
      register: homebrew_retry_molecule_spotify_app

    - name: Check which Taps are present
      ansible.builtin.command: brew tap
      changed_when: true
      register: homebrew_retry_molecule_taps

    - name: Assert telnet was Installed Correctly
      ansible.builtin.assert:
        that:
          - homebrew_retry_molecule_telnet_file.stat.exists
          - homebrew_retry_molecule_telnet_file.stat.executable
        msg: "The telnet binary must exist and be executable."

    - name: Assert App Cleaner was Installed Correctly
      ansible.builtin.assert:
        that:
          - homebrew_retry_molecule_cleaner_file.stat.exists
          - homebrew_retry_molecule_cleaner_file.stat.executable
        msg: "The App Cleaner binary must exist and be executable."

    - name: Assert Transmission was Installed Correctly
      ansible.builtin.assert:
        that:
          - homebrew_retry_molecule_transmission.stat.exists
          - homebrew_retry_molecule_transmission.stat.executable
        msg: "The Transmission binary must exist and be executable."

    - name: Assert Spotify was Installed Correctly
      ansible.builtin.assert:
        that:
          - homebrew_retry_molecule_spotify_file.stat.exists
          - homebrew_retry_molecule_spotify_file.stat.executable
          - homebrew_retry_molecule_spotify_app.stat.mode == "0775"
          - homebrew_retry_molecule_spotify_app.stat.gr_name == brew_targeted_casks_group
          - homebrew_retry_molecule_spotify_app.stat.pw_name == brew_user
        msg: "The Spotify binary must exist and be executable, and have the targeted permissions."

    - name: Assert Homebrew Taps were Installed Correctly
      ansible.builtin.assert:
        that:
          - brew_taps[0] in homebrew_retry_molecule_taps.stdout
        msg: "The configured homebrew taps must be present."
